from calculators import HopAddition as Hop

HOP_CHALLENGER = Hop('Challenger', alpha=7.1)
HOP_BREWERS_GOLD = Hop('Brewers Gold', alpha=5.5)
HOP_BULLION = Hop('Bullion', alpha=8)
HOP_CHALLENGER = Hop('Challenger', alpha=7.1)
HOP_EKG = Hop('Goldings (East Kent)', alpha=5)
HOP_FUGGLES = Hop('Fuggles', alpha=4.5)
HOP_WGOLDING = Hop('Goldings (Worc.)', alpha=5.3)
HOP_HALLERTAUER = Hop('Hallertauer', alpha=4.5)
HOP_NORTH_BREWER = Hop('North Brewer', alpha=7.5)
HOP_NORTHDOWN = Hop('Northdown', alpha=9.25)
HOP_PROGRESS = Hop('Progress', alpha=6.2)
HOP_SAAZ = Hop('Saaz', alpha=2.2)
HOP_STYRIAN_GOLDINGS = Hop('Styrian Goldings', alpha=4.5)
HOP_TARGET = Hop('Target', alpha=11.2)
HOP_TETTNANG = Hop('Tettnang', alpha=5)
HOP_WGV = Hop('WGV', alpha=6.3)
